set mapred.job.pool $JOB_POOL;

KEYWORD_COUNTS = LOAD '$WORDCOUNT_OUTPUT_FOLDER/*' USING PigStorage('\t') AS (
	keyword:chararray,
	count:int);

FILTERED_KEYWORD_COUNTS = FILTER KEYWORD_COUNTS BY (count > $WORDCOUNT_MINIMUM_THRESHOLD);

STORE FILTERED_KEYWORD_COUNTS INTO '$WORDCOUNT_FILTERED_OUTPUT_FOLDER';
